name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:      
  push:                  
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # ------ CONFIGURAÇÕES ESSENCIAIS ------
          user: ppeu1302
          template: classic
          base: header, activity, community, repositories, metadata

          # ------ COMMITS ------
          commits_authoring: ppeu1302

          # ------ LINGUAGENS MAIS USADAS ------
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, less
          plugin_languages_threshold: 1%
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # ------ ATIVIDADE ------
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 14
          plugin_activity_filter: all

          # ------ REPOSITÓRIOS ------
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, collaborator

          # ------ CONTRIBUIÇÕES ------
          plugin_followup: yes
          plugin_followup_sections: user, repositories

          # ------ GRÁFICOS ------
          plugin_lines: yes

          # ------ STATS DE GITHUB ------
          plugin_stars: yes
          plugin_stars_limit: 5

          # ------ GERA O ARQUIVO ------
          filename: github-metrics.svg
